name: Publish
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-cocoapods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to CocoaPods
        run: echo "Would run pod trunk push here"
