name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract Version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Build and Test
      run: |
        swift build -c release
        swift test
        
    - name: Create Release Notes
      id: release_notes
      run: |
        echo "## TraceWise iOS SDK v${{ steps.version.outputs.version }}" > release_notes.md
        echo "" >> release_notes.md
        echo "### Features" >> release_notes.md
        echo "- Complete iOS SDK implementation" >> release_notes.md
        echo "- Firebase Auth integration" >> release_notes.md
        echo "- GS1 Digital Link parser" >> release_notes.md
        echo "- EPCIS 2.0 compliant lifecycle events" >> release_notes.md
        echo "- CIRPASS product support" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Installation" >> release_notes.md
        echo "\`\`\`swift" >> release_notes.md
        echo ".package(url: \"https://github.com/tracewise/TraceWise-iOS.git\", from: \"${{ steps.version.outputs.version }}\")" >> release_notes.md
        echo "\`\`\`" >> release_notes.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: TraceWise iOS SDK v${{ steps.version.outputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}