name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Analysis
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: swift
        
    - name: Build for Analysis
      run: swift build
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
      
    - name: Dependency Check
      run: |
        swift package show-dependencies --format json > dependencies.json
        echo "Dependencies scanned successfully"